pipeline:
  identifier: Build_kafka_harness_demo_1687962942086
  name: Build kafka-harness-demo
  orgIdentifier: default
  projectIdentifier: harnesskafkademo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: tranthanhdeveloper/kafka-harness-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
