pipeline:
  identifier: Build_kafka_harness_demo_1687839338324
  name: Build kafka-harness-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: tranthanhdeveloper/kafka-harness-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  name: Run Tests with Intelligence
                  type: RunTests
                  identifier: Run_Tests_with_Intelligence
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: clean test
                    packages: org.apache.kafka,kafka.test,kafka.testkit,kafka.server,kafka.tools,kafka.examples,test.plugins
                    runOnlySelectedTests: true
                    preCommand: ls
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
